# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['gui_window.py'],
    pathex=[],
    binaries=[],
    datas=[('assets/eye.ico', 'assets')],
    hiddenimports=[
        'tobii_research',
        'pystray._darwin',  # macOS-specific
        'PIL._tkinter_finder',
        'customtkinter',
        'fastapi',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'app',
        'app.api',
        'app.config',
        'app.models',
        'app.models.gaze',
        'app.routers',
        'app.routers.tobii',
        'app.services',
        'app.services.tobii_service',
        'gui',
        'gui.service_manager',
        'gui.styles',
        'gui.widgets',
        'psutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Lexora',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/eye.ico',
)

app = BUNDLE(
    exe,
    name='Lexora.app',
    icon='assets/eye.ico',
    bundle_identifier='com.lexora.eyetracker',
    info_plist={
        'NSHighResolutionCapable': 'True',
        'LSUIElement': '1',
    },
)
