class Styles:
    """Lexora desktop service visual constants."""

    BRAND_CHARCOAL = "#1b2021"
    BRAND_OLIVE = "#51513d"
    BRAND_SAGE = "#a6a867"
    BRAND_KHAKI = "#e3dc95"
    BRAND_CREAM = "#e3dcc2"

    BG_COLOR = BRAND_CREAM
    CARD_BG = "#f3edd7"
    CARD_BG_LIGHT = "#ebe3c8"

    ACCENT_COLOR = BRAND_OLIVE
    ACCENT_HOVER = BRAND_CHARCOAL

    SUCCESS_COLOR = BRAND_SAGE
    SUCCESS_HOVER = BRAND_OLIVE
    SUCCESS_LIGHT = "#edf0c8"
    SUCCESS_DARK = BRAND_OLIVE

    DANGER_COLOR = "#9e5a5a"
    DANGER_HOVER = "#874848"

    SECONDARY_COLOR = "#74745a"
    SECONDARY_HOVER = BRAND_OLIVE

    WARNING_COLOR = "#c0a94f"
    INFO_LIGHT = BRAND_KHAKI
    INFO_DARK = BRAND_OLIVE

    BUTTON_DISABLED = "#c8c0aa"

    TEXT_PRIMARY = BRAND_CHARCOAL
    TEXT_SECONDARY = "#51513d"
    TEXT_MUTED = "#8a846f"

    BORDER_COLOR = "#c8c0aa"
    DIVIDER_COLOR = "#d4cbb6"

    FONT_FAMILY = "Segoe UI"
    FONT_FAMILY_MONO = "Consolas"
    FONT_SIZE_LARGE = 20
    FONT_SIZE_MEDIUM = 12
    FONT_SIZE_NORMAL = 10

    CORNER_RADIUS = 8
    CORNER_RADIUS_SM = 4
    PADDING = 20
    PADDING_SM = 12
