import { Question } from "@/lib/types";

export const QUESTION_BANK: Question[] = [
  {
    id: "q1",
    title: "Question 1",
    prompt: "Find the letter e in a 3x3 grid.",
    instruction:
      "Click the letter e as many times as you can before the timer ends.",
    audioText: "Find the letter e.",
    gridSize: 3,
    targetToken: "e",
    distractorTokens: ["a", "o", "c", "u", "i", "l", "n", "m", "r"],
  },
  {
    id: "q2",
    title: "Question 2",
    prompt: "Find the letter g in a 4x4 grid.",
    instruction:
      "Click the letter g as many times as you can before the timer ends.",
    audioText: "Find the letter g.",
    gridSize: 4,
    targetToken: "g",
    distractorTokens: ["q", "c", "j", "b", "d", "p", "o", "a", "s", "y"],
  },
  {
    id: "q3",
    title: "Question 3",
    prompt: "Find the letter b in a 5x5 grid.",
    instruction:
      "Click the letter b as many times as you can before the timer ends.",
    audioText: "Find the letter b.",
    gridSize: 5,
    targetToken: "b",
    distractorTokens: ["d", "p", "q", "g", "h", "k", "l", "n", "m", "r"],
  },
  {
    id: "q4",
    title: "Question 4",
    prompt: "Find the letter d in a 6x6 grid.",
    instruction:
      "Click the letter d as many times as you can before the timer ends.",
    audioText: "Find the letter d.",
    gridSize: 6,
    targetToken: "d",
    distractorTokens: ["b", "p", "q", "o", "a", "g", "l", "h", "c", "e"],
  },
  {
    id: "q5",
    title: "Question 5",
    prompt: "Find the syllable ba in a 5x5 grid.",
    instruction:
      "Click the syllable ba as many times as you can before the timer ends.",
    audioText: "Find the syllable ba.",
    gridSize: 5,
    targetToken: "ba",
    distractorTokens: [
      "da",
      "pa",
      "ga",
      "be",
      "bo",
      "ab",
      "la",
      "na",
      "ma",
      "ra",
    ],
  },
  {
    id: "q6",
    title: "Question 6",
    prompt: "Find the syllable gar in a 5x5 grid.",
    instruction:
      "Click the syllable gar as many times as you can before the timer ends.",
    audioText: "Find the syllable gar.",
    gridSize: 5,
    targetToken: "gar",
    distractorTokens: [
      "bar",
      "car",
      "par",
      "dar",
      "gal",
      "gan",
      "gor",
      "ger",
      "sar",
      "lar",
    ],
  },
  {
    id: "q7",
    title: "Question 7",
    prompt: "Find the syllable pla in a 5x5 grid.",
    instruction:
      "Click the syllable pla as many times as you can before the timer ends.",
    audioText: "Find the syllable pla.",
    gridSize: 5,
    targetToken: "pla",
    distractorTokens: [
      "bla",
      "pra",
      "ple",
      "plo",
      "plu",
      "pna",
      "pfa",
      "cla",
      "fla",
      "sla",
    ],
  },
  {
    id: "q8",
    title: "Question 8",
    prompt: "Find the syllable bla in a 5x5 grid.",
    instruction:
      "Click the syllable bla as many times as you can before the timer ends.",
    audioText: "Find the syllable bla.",
    gridSize: 5,
    targetToken: "bla",
    distractorTokens: [
      "pla",
      "gla",
      "ble",
      "blo",
      "bna",
      "bra",
      "bli",
      "dla",
      "bua",
      "cla",
    ],
  },
  {
    id: "q9",
    title: "Question 9",
    prompt: "Find the syllable str in a 6x6 grid.",
    instruction:
      "Click the syllable str as many times as you can before the timer ends.",
    audioText: "Find the syllable str.",
    gridSize: 6,
    targetToken: "str",
    distractorTokens: [
      "shr",
      "scr",
      "spr",
      "thr",
      "skr",
      "snr",
      "slr",
      "sdr",
      "srt",
      "trs",
    ],
  },
  {
    id: "q10",
    title: "Question 10",
    prompt: "Find the word bake in a 3x3 grid.",
    instruction:
      "Click the word bake as many times as you can before the timer ends.",
    audioText: "Find the word bake.",
    gridSize: 3,
    targetToken: "bake",
    distractorTokens: [
      "lake",
      "fake",
      "make",
      "rake",
      "pace",
      "base",
      "lace",
      "dake",
      "gake",
    ],
  },
  {
    id: "q11",
    title: "Question 11",
    prompt: "Find the word game in a 4x4 grid.",
    instruction:
      "Click the word game as many times as you can before the timer ends.",
    audioText: "Find the word game.",
    gridSize: 4,
    targetToken: "game",
    distractorTokens: [
      "same",
      "came",
      "gate",
      "fame",
      "gale",
      "name",
      "gane",
      "gime",
      "gome",
      "gaze",
    ],
  },
  {
    id: "q12",
    title: "Question 12",
    prompt: "Find the word stone in a 4x4 grid.",
    instruction:
      "Click the word stone as many times as you can before the timer ends.",
    audioText: "Find the word stone.",
    gridSize: 4,
    targetToken: "stone",
    distractorTokens: [
      "stane",
      "stole",
      "store",
      "shone",
      "atone",
      "stine",
      "scone",
      "stome",
      "stune",
      "spone",
    ],
  },
  {
    id: "q13",
    title: "Question 13",
    prompt: "Find the word market in a 4x4 grid.",
    instruction:
      "Click the word market as many times as you can before the timer ends.",
    audioText: "Find the word market.",
    gridSize: 4,
    targetToken: "market",
    distractorTokens: [
      "marker",
      "marset",
      "marget",
      "martet",
      "marlet",
      "makret",
      "markel",
      "parket",
      "morket",
      "marcet",
    ],
  },
  {
    id: "q14",
    title: "Question 14",
    prompt: "Find the different letter in a 5x5 grid.",
    instruction:
      "Click the different letter as many times as you can before the timer ends.",
    audioText: "Find the different letter.",
    gridSize: 5,
    targetToken: "a",
    distractorTokens: ["o"],
    targetRepeatCount: 1,
  },
  {
    id: "q15",
    title: "Question 15",
    prompt: "Find the different letter in a 5x5 grid.",
    instruction:
      "Click the different letter as many times as you can before the timer ends.",
    audioText: "Find the different letter.",
    gridSize: 5,
    targetToken: "b",
    distractorTokens: ["d"],
    targetRepeatCount: 1,
  },
  {
    id: "q16",
    title: "Question 16",
    prompt: "Find the different letter in a 5x5 grid.",
    instruction:
      "Click the different letter as many times as you can before the timer ends.",
    audioText: "Find the different letter.",
    gridSize: 5,
    targetToken: "p",
    distractorTokens: ["q"],
    targetRepeatCount: 1,
  },
  {
    id: "q17",
    title: "Question 17",
    prompt: "Find the different letter in a 5x5 grid.",
    instruction:
      "Click the different letter as many times as you can before the timer ends.",
    audioText: "Find the different letter.",
    gridSize: 5,
    targetToken: "u",
    distractorTokens: ["v"],
    targetRepeatCount: 1,
  },
  {
    id: "q18",
    title: "Question 18",
    prompt: "Choose the correct spelling of the pseudo-word in a 3x3 grid.",
    instruction:
      "Click the correct spelling as many times as you can before the timer ends.",
    audioText: "Find the pseudo-word blontek.",
    gridSize: 3,
    targetToken: "blontek",
    distractorTokens: [
      "bontek",
      "blonket",
      "blontec",
      "brontek",
      "blonted",
      "plontek",
      "blontest",
      "blonteg",
    ],
  },
  {
    id: "q19",
    title: "Question 19",
    prompt: "Choose the correct spelling of the pseudo-word in a 3x3 grid.",
    instruction:
      "Click the correct spelling as many times as you can before the timer ends.",
    audioText: "Find the pseudo-word strampit.",
    gridSize: 3,
    targetToken: "strampit",
    distractorTokens: [
      "stamprit",
      "trampit",
      "strampid",
      "strambit",
      "scampit",
      "strampot",
      "strampig",
      "strampir",
    ],
  },
  {
    id: "q20",
    title: "Question 20",
    prompt: "Choose the correct spelling of the word in a 3x3 grid.",
    instruction:
      "Click the correct spelling as many times as you can before the timer ends.",
    audioText: "Find the word window.",
    gridSize: 3,
    targetToken: "window",
    distractorTokens: [
      "windwo",
      "widnow",
      "windo",
      "winndow",
      "wimdow",
      "windor",
      "winrow",
      "wimdow",
    ],
  },
  {
    id: "q21",
    title: "Question 21",
    prompt: "Choose the correct spelling of the word in a 3x3 grid.",
    instruction:
      "Click the correct spelling as many times as you can before the timer ends.",
    audioText: "Find the word planet.",
    gridSize: 3,
    targetToken: "planet",
    distractorTokens: [
      "plnaet",
      "planat",
      "plannet",
      "planer",
      "palnet",
      "plamet",
      "plonet",
      "planed",
    ],
  },
  {
    id: "q22",
    title: "Question 22",
    prompt: "Find the missing letter in the word.",
    instruction:
      "Click the missing letter as many times as you can before the timer ends.",
    audioText: "Find the missing letter.",
    interactionType: "letterChoices",
    choiceCount: 5,
    visualCue: "h _ use",
    gridSize: 3,
    targetToken: "o",
    distractorTokens: ["u", "a", "e", "i"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "h _ use",
        targetToken: "o",
        distractorTokens: ["u", "a", "e", "i"],
      },
      {
        visualCue: "c _ t",
        targetToken: "a",
        distractorTokens: ["u", "o", "e", "i"],
      },
      {
        visualCue: "pl _ ne",
        targetToken: "a",
        distractorTokens: ["e", "i", "o", "u"],
      },
      {
        visualCue: "sm _ le",
        targetToken: "i",
        distractorTokens: ["e", "a", "o", "u"],
      },
      {
        visualCue: "tr _ in",
        targetToken: "a",
        distractorTokens: ["e", "i", "o", "u"],
      },
      {
        visualCue: "b _ ok",
        targetToken: "o",
        distractorTokens: ["a", "e", "i", "u"],
      },
      {
        visualCue: "st _ ne",
        targetToken: "o",
        distractorTokens: ["a", "e", "i", "u"],
      },
      {
        visualCue: "gr _ pe",
        targetToken: "a",
        distractorTokens: ["e", "i", "o", "u"],
      },
      {
        visualCue: "sh _ p",
        targetToken: "i",
        distractorTokens: ["a", "e", "o", "u"],
      },
      {
        visualCue: "dr _ nk",
        targetToken: "i",
        distractorTokens: ["a", "e", "o", "u"],
      },
      {
        visualCue: "br _ dge",
        targetToken: "i",
        distractorTokens: ["a", "e", "o", "u"],
      },
      {
        visualCue: "cl _ ck",
        targetToken: "o",
        distractorTokens: ["a", "e", "i", "u"],
      },
      {
        visualCue: "fl _ wer",
        targetToken: "o",
        distractorTokens: ["a", "e", "i", "u"],
      },
    ],
  },
  {
    id: "q23",
    title: "Question 23",
    prompt: "Find the wrong letter in the word.",
    instruction:
      "Click the wrong letter in the word as many times as you can before the timer ends.",
    audioText: "Find the wrong letter.",
    interactionType: "wordLetters",
    visualCue: "hause",
    gridSize: 3,
    targetToken: "a",
    distractorTokens: ["h", "u", "s", "e"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "houzse",
        targetToken: "z",
        distractorTokens: ["h", "o", "u", "s", "e"],
      },
      {
        visualCue: "friepnd",
        targetToken: "p",
        distractorTokens: ["f", "r", "i", "e", "n", "d"],
      },
      {
        visualCue: "plaqne",
        targetToken: "q",
        distractorTokens: ["p", "l", "a", "n", "e"],
      },
      {
        visualCue: "smilfe",
        targetToken: "f",
        distractorTokens: ["s", "m", "i", "l", "e"],
      },
      {
        visualCue: "trakin",
        targetToken: "k",
        distractorTokens: ["t", "r", "a", "i", "n"],
      },
      {
        visualCue: "bookm",
        targetToken: "m",
        distractorTokens: ["b", "o", "k", "a", "e"],
      },
      {
        visualCue: "stonwe",
        targetToken: "w",
        distractorTokens: ["s", "t", "o", "n", "e"],
      },
      {
        visualCue: "gracpe",
        targetToken: "c",
        distractorTokens: ["g", "r", "a", "p", "e"],
      },
      {
        visualCue: "shiup",
        targetToken: "u",
        distractorTokens: ["s", "h", "i", "p", "a"],
      },
      {
        visualCue: "drinvk",
        targetToken: "v",
        distractorTokens: ["d", "r", "i", "n", "k"],
      },
      {
        visualCue: "bridgze",
        targetToken: "z",
        distractorTokens: ["b", "r", "i", "d", "g", "e"],
      },
      {
        visualCue: "cloqck",
        targetToken: "q",
        distractorTokens: ["c", "l", "o", "k", "a"],
      },
      {
        visualCue: "flowber",
        targetToken: "b",
        distractorTokens: ["f", "l", "o", "w", "e", "r"],
      },
    ],
  },
  {
    id: "q24",
    title: "Question 24",
    prompt: "Find the wrong word in the sentence.",
    instruction:
      "Click the wrong word in the sentence as many times as you can before the timer ends.",
    audioText: "Find the wrong word.",
    interactionType: "sentenceWords",
    visualCue: "She went to the bakery to compare a cake.",
    gridSize: 3,
    targetToken: "compare",
    distractorTokens: ["she", "went", "to", "the", "bakery", "a", "cake"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "She went to the bakery to compare a cake.",
        targetToken: "compare",
        distractorTokens: ["she", "went", "to", "the", "bakery", "a", "cake"],
      },
      {
        visualCue: "He opened the umbrella because it was sunny.",
        targetToken: "umbrella",
        distractorTokens: ["he", "opened", "because", "it", "was", "sunny"],
      },
      {
        visualCue: "The farmer milked the tree every morning.",
        targetToken: "tree",
        distractorTokens: ["the", "farmer", "milked", "every", "morning"],
      },
      {
        visualCue: "Mina wore her boots to swim in the pool.",
        targetToken: "boots",
        distractorTokens: [
          "mina",
          "wore",
          "her",
          "to",
          "swim",
          "in",
          "the",
          "pool",
        ],
      },
      {
        visualCue: "They put the soup in the freezer to make it hot.",
        targetToken: "hot",
        distractorTokens: [
          "they",
          "put",
          "the",
          "soup",
          "in",
          "freezer",
          "to",
          "make",
          "it",
        ],
      },
    ],
  },
  {
    id: "q25",
    title: "Question 25",
    prompt: "Find the wrong grammatical part in the sentence.",
    instruction:
      "Click the wrong grammatical part as many times as you can before the timer ends.",
    audioText: "Find the wrong grammatical part.",
    interactionType: "sentenceWords",
    visualCue: "She is a end of the hall.",
    gridSize: 3,
    targetToken: "a",
    distractorTokens: ["she", "is", "end", "of", "the", "hall"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "She is a end of the hall.",
        targetToken: "a",
        distractorTokens: ["she", "is", "end", "of", "the", "hall"],
      },
      {
        visualCue: "I arrived to Monday morning.",
        targetToken: "to",
        distractorTokens: ["i", "arrived", "monday", "morning"],
      },
      {
        visualCue: "He gave the book at his friend.",
        targetToken: "at",
        distractorTokens: ["he", "gave", "the", "book", "his", "friend"],
      },
      {
        visualCue: "They are interested on music.",
        targetToken: "on",
        distractorTokens: ["they", "are", "interested", "music"],
      },
      {
        visualCue: "We listened a story before bed.",
        targetToken: "a",
        distractorTokens: ["we", "listened", "story", "before", "bed"],
      },
    ],
  },
  {
    id: "q26",
    title: "Question 26",
    prompt: "Fix the wrong letter in the word.",
    instruction: "Click the wrong letter, then choose the correct replacement.",
    audioText: "Fix the wrong letter in the word.",
    interactionType: "letterReplacement",
    visualCue: "tabke",
    gridSize: 3,
    targetToken: "table",
    distractorTokens: ["tabke", "tabla", "tablr", "tabme", "tabre"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "tabke",
        targetToken: "table",
        distractorTokens: ["tabke", "tabla", "tablr", "tabme", "tabre"],
      },
      {
        visualCue: "greeb",
        targetToken: "green",
        distractorTokens: ["greeb", "grean", "greem", "greel", "greer"],
      },
      {
        visualCue: "chiar",
        targetToken: "chair",
        distractorTokens: ["chiar", "chaar", "choir", "chairr", "chier"],
      },
      {
        visualCue: "breadt",
        targetToken: "bread",
        distractorTokens: ["breadt", "briad", "breud", "broad", "breld"],
      },
      {
        visualCue: "ligth",
        targetToken: "light",
        distractorTokens: ["ligth", "lighr", "lignt", "lightt", "ligrt"],
      },
      {
        visualCue: "moues",
        targetToken: "mouse",
        distractorTokens: ["moues", "mousa", "mousr", "mousl", "moust"],
      },
      {
        visualCue: "plnat",
        targetToken: "plant",
        distractorTokens: ["plnat", "planr", "plent", "plamt", "plart"],
      },
      {
        visualCue: "houes",
        targetToken: "house",
        distractorTokens: ["houes", "housa", "housr", "hoube", "hoyse"],
      },
      {
        visualCue: "milt",
        targetToken: "milk",
        distractorTokens: ["milt", "milp", "milm", "miln", "mils"],
      },
      {
        visualCue: "leafs",
        targetToken: "leaf",
        distractorTokens: ["leafs", "leafd", "leafm", "leafn", "leafr"],
      },
    ],
  },
  {
    id: "q27",
    title: "Question 27",
    prompt: "Arrange the scrambled letters to make the correct word.",
    instruction:
      "Click the letters in order to arrange them and form the correct word at the top.",
    audioText: "Arrange the letters to make the word.",
    interactionType: "letterArrangement",
    visualCue: "e,v,s,e,n",
    gridSize: 3,
    targetToken: "seven",
    distractorTokens: [
      "sever",
      "sieve",
      "venes",
      "evens",
      "scene",
      "serve",
      "event",
    ],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "e,v,s,e,n",
        targetToken: "seven",
        distractorTokens: ["sever", "sieve", "venes", "evens", "scene"],
      },
      {
        visualCue: "a,p,p,l,e",
        targetToken: "apple",
        distractorTokens: ["apply", "appel", "papel", "pearl", "allee"],
      },
      {
        visualCue: "w,a,t,e,r",
        targetToken: "water",
        distractorTokens: ["waver", "tower", "wrote", "treat", "wears"],
      },
      {
        visualCue: "s,c,h,o,o,l",
        targetToken: "school",
        distractorTokens: ["shoolc", "choosl", "cohsol", "shcool", "chools"],
      },
      {
        visualCue: "w,i,n,t,e,r",
        targetToken: "winter",
        distractorTokens: ["writer", "interw", "wintre", "twiner", "winert"],
      },
    ],
  },
  {
    id: "q28",
    title: "Question 28",
    prompt: "Arrange the short syllables to make the word.",
    instruction: "Click the syllables in order to form the word at the top.",
    audioText: "Arrange the short syllables.",
    interactionType: "syllableArrangement",
    visualCue: "sun,set",
    gridSize: 3,
    targetToken: "sunset",
    distractorTokens: ["sunest", "susnet", "sunsat", "sunsett", "sunst"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "sun,set",
        targetToken: "sunset",
        distractorTokens: ["sunest", "susnet", "sunsat", "sunsett"],
      },
      {
        visualCue: "ro,bot",
        targetToken: "robot",
        distractorTokens: ["roobt", "rboot", "robet", "robott", "robat"],
      },
      {
        visualCue: "pa,per",
        targetToken: "paper",
        distractorTokens: ["paepr", "papre", "papar", "paperr", "paepr"],
      },
      {
        visualCue: "mu,sic",
        targetToken: "music",
        distractorTokens: ["musci", "muisc", "musac", "musick", "msuic"],
      },
      {
        visualCue: "hap,py",
        targetToken: "happy",
        distractorTokens: ["hpayp", "hapyp", "happi", "happyy", "haapy"],
      },
    ],
  },
  {
    id: "q29",
    title: "Question 29",
    prompt:
      "Separate the connected text into a meaningful sentence by choosing the correct segmentation.",
    instruction:
      "Read the connected text and click the correctly separated sentence.",
    audioText: "Choose the correctly separated sentence.",
    interactionType: "sentenceSegmentationChoices",
    choiceCount: 4,
    visualCue: "iturnedtwentytwotoday",
    gridSize: 2,
    targetToken: "i turned twenty two today",
    distractorTokens: [
      "iturned twenty two today",
      "i turnedtwenty two today",
      "i turned twenty twotoday",
    ],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "iturnedtwentytwotoday",
        targetToken: "i turned twenty two today",
        distractorTokens: [
          "iturned twenty two today",
          "i turnedtwenty two today",
          "i turned twenty twotoday",
        ],
      },
      {
        visualCue: "mymotherreadsmeastory",
        targetToken: "my mother reads me a story",
        distractorTokens: [
          "mymother reads me a story",
          "my motherreads me a story",
          "my mother reads me astory",
        ],
      },
      {
        visualCue: "thecatsleepsonthesofa",
        targetToken: "the cat sleeps on the sofa",
        distractorTokens: [
          "thecat sleeps on the sofa",
          "the catsleeps on the sofa",
          "the cat sleeps onthe sofa",
        ],
      },
      {
        visualCue: "wegototheparkwithmycousin",
        targetToken: "we go to the park with my cousin",
        distractorTokens: [
          "wego to the park with my cousin",
          "we go tothe park with my cousin",
          "we go to the parkwith my cousin",
        ],
      },
      {
        visualCue: "thechocolatecakeisready",
        targetToken: "the chocolate cake is ready",
        distractorTokens: [
          "thechocolate cake is ready",
          "the chocolatecake is ready",
          "the chocolate cakeis ready",
        ],
      },
      {
        visualCue: "mybrotherplayswiththeball",
        targetToken: "my brother plays with the ball",
        distractorTokens: [
          "mybrother plays with the ball",
          "my brotherplays with the ball",
          "my brother plays withthe ball",
        ],
      },
      {
        visualCue: "theteacherwritesontheboard",
        targetToken: "the teacher writes on the board",
        distractorTokens: [
          "theteacher writes on the board",
          "the teacherwrites on the board",
          "the teacher writes onthe board",
        ],
      },
      {
        visualCue: "shewashesherhandsbeforelunch",
        targetToken: "she washes her hands before lunch",
        distractorTokens: [
          "shewashes her hands before lunch",
          "she washesher hands before lunch",
          "she washes her handsbefore lunch",
        ],
      },
      {
        visualCue: "thechildrenrunintheyard",
        targetToken: "the children run in the yard",
        distractorTokens: [
          "thechildren run in the yard",
          "the childrenrun in the yard",
          "the children run inthe yard",
        ],
      },
      {
        visualCue: "wewatchamovieafterdinner",
        targetToken: "we watch a movie after dinner",
        distractorTokens: [
          "wewatch a movie after dinner",
          "we watcha movie after dinner",
          "we watch a movieafter dinner",
        ],
      },
      {
        visualCue: "thebabyisplayingwithblocks",
        targetToken: "the baby is playing with blocks",
        distractorTokens: [
          "thebaby is playing with blocks",
          "the babyis playing with blocks",
          "the baby is playing withblocks",
        ],
      },
      {
        visualCue: "myfriendbringsabluenotebook",
        targetToken: "my friend brings a blue notebook",
        distractorTokens: [
          "myfriend brings a blue notebook",
          "my friendbrings a blue notebook",
          "my friend brings ablue notebook",
        ],
      },
      {
        visualCue: "wecleanourroomeverymorning",
        targetToken: "we clean our room every morning",
        distractorTokens: [
          "weclean our room every morning",
          "we cleanour room every morning",
          "we clean our roomevery morning",
        ],
      },
    ],
  },
  {
    id: "q30",
    title: "Question 30",
    prompt: "Memorize the short letter sequence, then type it.",
    instruction: "Watch for 3 seconds, then type from memory.",
    audioText: "Memorize, then type.",
    interactionType: "typedSequenceRecall",
    visualCue: "mip",
    gridSize: 3,
    targetToken: "mip",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "rato",
        targetToken: "rato",
        distractorTokens: [],
      },
      {
        visualCue: "luse",
        targetToken: "luse",
        distractorTokens: [],
      },
      {
        visualCue: "voni",
        targetToken: "voni",
        distractorTokens: [],
      },
    ],
  },
  {
    id: "q31",
    title: "Question 31",
    prompt: "Listen and type each short real word.",
    instruction: "After each spoken word, type it exactly.",
    audioText: "Listen and type the short words.",
    interactionType: "typedSequenceRecall",
    visualCue: "",
    gridSize: 3,
    targetToken: "apple",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "",
        targetToken: "water",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "happy",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "music",
        distractorTokens: [],
      },
    ],
  },
  {
    id: "q32",
    title: "Question 32",
    prompt: "Listen and type each short made-up word.",
    instruction: "After each spoken made-up word, type it exactly.",
    audioText: "Listen and type the short made up words.",
    interactionType: "typedSequenceRecall",
    visualCue: "",
    gridSize: 3,
    targetToken: "mepo",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "",
        targetToken: "savi",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "luno",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "tromi",
        distractorTokens: [],
      },
    ],
  },
];
