import { Question } from "@/features/gamified-test/lib/types";

export const QUESTION_BANK_AR: Question[] = [
  {
    id: "q1",
    title: "السؤال 1",
    prompt: "اعثر على الحرف ب في الشبكة",
    instruction: "اضغط على كل حرف ب تراه قبل انتهاء الوقت",
    audioText: "اعثر على الحرف ب",
    gridSize: 3,
    targetToken: "ب",
    distractorTokens: ["ت", "ث", "ن", "ي"],
  },
  {
    id: "q2",
    title: "السؤال 2",
    prompt: "اعثر على الحرف ج في الشبكة",
    instruction: "اضغط على كل حرف ج تراه قبل انتهاء الوقت",
    audioText: "اعثر على الحرف ج",
    gridSize: 4,
    targetToken: "ج",
    distractorTokens: ["ح", "خ", "ع", "غ"],
  },
  {
    id: "q3",
    title: "السؤال 3",
    prompt: "اعثر على الحرف د في الشبكة",
    instruction: "اضغط على كل حرف د تراه قبل انتهاء الوقت",
    audioText: "اعثر على الحرف د",
    gridSize: 5,
    targetToken: "د",
    distractorTokens: ["ذ", "ر", "ز", "و"],
  },
  {
    id: "q4",
    title: "السؤال 4",
    prompt: "اعثر على الحرف س في الشبكة",
    instruction: "اضغط على كل حرف س تراه قبل انتهاء الوقت",
    audioText: "اعثر على الحرف س",
    gridSize: 6,
    targetToken: "س",
    distractorTokens: ["ش", "ص", "ض", "ث"],
  },
  {
    id: "q5",
    title: "السؤال 5",
    prompt: "اعثر على المقطع با في الشبكة",
    instruction: "اضغط على المقطع با أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على المقطع با",
    gridSize: 5,
    targetToken: "با",
    distractorTokens: ["تا", "ثا", "نا", "يا", "بي", "بو", "بن"],
  },
  {
    id: "q6",
    title: "السؤال 6",
    prompt: "اعثر على المقطع دار في الشبكة",
    instruction: "اضغط على المقطع دار أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على المقطع دار",
    gridSize: 5,
    targetToken: "دار",
    distractorTokens: ["ذار", "زار", "رار", "دير", "دور", "نار", "بار"],
  },
  {
    id: "q7",
    title: "السؤال 7",
    prompt: "اعثر على المقطع بِرا في الشبكة",
    instruction: "اضغط على المقطع بِرا أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على المقطع بِرا",
    gridSize: 5,
    targetToken: "برا",
    distractorTokens: ["ترا", "ثرا", "نرا", "يرا", "بزا", "بدا", "برو"],
  },
  {
    id: "q8",
    title: "السؤال 8",
    prompt: "اعثر على المقطع بلا في الشبكة",
    instruction: "اضغط على المقطع بلا أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على المقطع بلا",
    gridSize: 5,
    targetToken: "بلا",
    distractorTokens: ["تلا", "ثلا", "نلا", "يلا", "بلو", "بلي", "ملا"],
  },
  {
    id: "q9",
    title: "السؤال 9",
    prompt: "اعثر على المقطع سِتر في الشبكة",
    instruction: "اضغط على المقطع ستر أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على المقطع ستر",
    gridSize: 6,
    targetToken: "ستر",
    distractorTokens: ["شتر", "صتر", "ستز", "سطر", "ستن", "ستل", "ثتر"],
  },
  {
    id: "q10",
    title: "السؤال 10",
    prompt: "اعثر على الكلمة بيت في الشبكة",
    instruction: "اضغط على الكلمة بيت أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على الكلمة بيت",
    gridSize: 3,
    targetToken: "بيت",
    distractorTokens: ["تيت", "ثيت", "نيت", "بيد", "بيز", "بيث", "بنت"],
  },
  {
    id: "q11",
    title: "السؤال 11",
    prompt: "اعثر على الكلمة كتاب في الشبكة",
    instruction: "اضغط على الكلمة كتاب أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على الكلمة كتاب",
    gridSize: 4,
    targetToken: "كتاب",
    distractorTokens: ["كثاب", "كتاث", "كتان", "كتاد", "كناب", "قتاب"],
  },
  {
    id: "q12",
    title: "السؤال 12",
    prompt: "اعثر على الكلمة مدرسة في الشبكة",
    instruction: "اضغط على الكلمة مدرسة أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على الكلمة مدرسة",
    gridSize: 4,
    targetToken: "مدرسة",
    distractorTokens: ["مذرسة", "مدرزة", "مدرشة", "مدرصة", "مدرسه", "مدرثة"],
  },
  {
    id: "q13",
    title: "السؤال 13",
    prompt: "اعثر على الكلمة مكتبة في الشبكة",
    instruction: "اضغط على الكلمة مكتبة أكبر عدد ممكن قبل انتهاء الوقت",
    audioText: "اعثر على الكلمة مكتبة",
    gridSize: 4,
    targetToken: "مكتبة",
    distractorTokens: ["مكثبة", "مكتثة", "مكتنة", "مقتبة", "مكتبه", "مكتية"],
  },
  {
    id: "q14",
    title: "السؤال 14",
    prompt: "اعثر على الحرف المختلف في الشبكة",
    instruction: "اضغط على الحرف الذي يختلف عن الباقين قبل انتهاء الوقت",
    audioText: "اعثر على الحرف المختلف",
    gridSize: 5,
    targetToken: "ب",
    distractorTokens: ["ت"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "Variant 2",
        targetToken: "ت",
        distractorTokens: ["ب"],
      },
      {
        visualCue: "Variant 3",
        targetToken: "ث",
        distractorTokens: ["ب"],
      },
      {
        visualCue: "Variant 4",
        targetToken: "ب",
        distractorTokens: ["ث"],
      },
      {
        visualCue: "Variant 5",
        targetToken: "ن",
        distractorTokens: ["ت"],
      },
      {
        visualCue: "Variant 6",
        targetToken: "ت",
        distractorTokens: ["ن"],
      },
      {
        visualCue: "Variant 7",
        targetToken: "ي",
        distractorTokens: ["ب"],
      },
      {
        visualCue: "Variant 8",
        targetToken: "ب",
        distractorTokens: ["ن"],
      },
    ],
  },
  {
    id: "q15",
    title: "السؤال 15",
    prompt: "اعثر على الحرف المختلف في الشبكة",
    instruction: "اضغط على الحرف الذي يختلف عن الباقين قبل انتهاء الوقت",
    audioText: "اعثر على الحرف المختلف",
    gridSize: 5,
    targetToken: "ج",
    distractorTokens: ["ح"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "Variant 2",
        targetToken: "ح",
        distractorTokens: ["ج"],
      },
      {
        visualCue: "Variant 3",
        targetToken: "خ",
        distractorTokens: ["ح"],
      },
      {
        visualCue: "Variant 4",
        targetToken: "ح",
        distractorTokens: ["خ"],
      },
      {
        visualCue: "Variant 5",
        targetToken: "ج",
        distractorTokens: ["خ"],
      },
      {
        visualCue: "Variant 6",
        targetToken: "ع",
        distractorTokens: ["غ"],
      },
      {
        visualCue: "Variant 7",
        targetToken: "غ",
        distractorTokens: ["ع"],
      },
      {
        visualCue: "Variant 8",
        targetToken: "ج",
        distractorTokens: ["ع"],
      },
    ],
  },
  {
    id: "q16",
    title: "السؤال 16",
    prompt: "اعثر على الحرف المختلف في الشبكة",
    instruction: "اضغط على الحرف الذي يختلف عن الباقين قبل انتهاء الوقت",
    audioText: "اعثر على الحرف المختلف",
    gridSize: 5,
    targetToken: "د",
    distractorTokens: ["ذ"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "Variant 2",
        targetToken: "ذ",
        distractorTokens: ["د"],
      },
      {
        visualCue: "Variant 3",
        targetToken: "ر",
        distractorTokens: ["ز"],
      },
      {
        visualCue: "Variant 4",
        targetToken: "ز",
        distractorTokens: ["ر"],
      },
      {
        visualCue: "Variant 5",
        targetToken: "د",
        distractorTokens: ["ر"],
      },
      {
        visualCue: "Variant 6",
        targetToken: "ذ",
        distractorTokens: ["ز"],
      },
      {
        visualCue: "Variant 7",
        targetToken: "ر",
        distractorTokens: ["د"],
      },
      {
        visualCue: "Variant 8",
        targetToken: "ز",
        distractorTokens: ["ذ"],
      },
    ],
  },
  {
    id: "q17",
    title: "السؤال 17",
    prompt: "اعثر على الحرف المختلف في الشبكة",
    instruction: "اضغط على الحرف الذي يختلف عن الباقين قبل انتهاء الوقت",
    audioText: "اعثر على الحرف المختلف",
    gridSize: 5,
    targetToken: "س",
    distractorTokens: ["ش"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "Variant 2",
        targetToken: "ش",
        distractorTokens: ["س"],
      },
      {
        visualCue: "Variant 3",
        targetToken: "ص",
        distractorTokens: ["ض"],
      },
      {
        visualCue: "Variant 4",
        targetToken: "ض",
        distractorTokens: ["ص"],
      },
      {
        visualCue: "Variant 5",
        targetToken: "س",
        distractorTokens: ["ص"],
      },
      {
        visualCue: "Variant 6",
        targetToken: "ط",
        distractorTokens: ["ظ"],
      },
      {
        visualCue: "Variant 7",
        targetToken: "ظ",
        distractorTokens: ["ط"],
      },
      {
        visualCue: "Variant 8",
        targetToken: "ش",
        distractorTokens: ["ض"],
      },
    ],
  },
  {
    id: "q18",
    title: "السؤال 18",
    prompt: "اختر التهجئة الصحيحة للكلمة غير الحقيقية",
    instruction: "استمع إلى الكلمة ثم اضغط على تهجئتها الصحيحة",
    audioText: "اعثر على الكلمة بلونتك",
    gridSize: 3,
    targetToken: "بلونتك",
    distractorTokens: ["تلونتك", "نلونتك", "بلونذك", "بلونتق", "بلونتث"],
  },
  {
    id: "q19",
    title: "السؤال 19",
    prompt: "اختر التهجئة الصحيحة للكلمة غير الحقيقية",
    instruction: "استمع إلى الكلمة ثم اضغط على تهجئتها الصحيحة",
    audioText: "اعثر على الكلمة ستراميت",
    gridSize: 3,
    targetToken: "ستراميت",
    distractorTokens: ["شتراميت", "صتراميت", "ستراميث", "سطراميت", "ستراميد"],
  },
  {
    id: "q20",
    title: "السؤال 20",
    prompt: "اختر التهجئة الصحيحة للكلمة",
    instruction: "استمع إلى الكلمة ثم اضغط على تهجئتها الصحيحة",
    audioText: "اعثر على الكلمة نافذة",
    gridSize: 3,
    targetToken: "نافذة",
    distractorTokens: ["نافده", "نافزة", "نافضة", "ناقذة", "نافذه"],
  },
  {
    id: "q21",
    title: "السؤال 21",
    prompt: "اختر التهجئة الصحيحة للكلمة",
    instruction: "استمع إلى الكلمة ثم اضغط على تهجئتها الصحيحة",
    audioText: "اعثر على الكلمة قلم",
    gridSize: 3,
    targetToken: "قلم",
    distractorTokens: ["كلم", "فلم", "قنم", "قلن", "قلب"],
  },
  {
    id: "q22",
    title: "السؤال 22",
    prompt: "اختر الحرف الناقص في الكلمة",
    instruction: "اضغط على الحرف الصحيح الذي يكمل الكلمة",
    audioText: "اختر الحرف الناقص",
    interactionType: "letterChoices",
    choiceCount: 5,
    visualCue: "بـ_ت",
    gridSize: 3,
    targetToken: "ي",
    distractorTokens: ["ا", "و", "ن", "ث"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "قـ_م",
        targetToken: "ل",
        distractorTokens: ["ن", "ب", "ر", "ت"],
      },
      {
        visualCue: "مـ_رسة",
        targetToken: "د",
        distractorTokens: ["ذ", "ز", "ر", "ب"],
      },
      {
        visualCue: "كـ_اب",
        targetToken: "ت",
        distractorTokens: ["ث", "ب", "ن", "د"],
      },
      {
        visualCue: "وـ_دة",
        targetToken: "ر",
        distractorTokens: ["ز", "د", "ذ", "ن"],
      },
      {
        visualCue: "شـ_س",
        targetToken: "م",
        distractorTokens: ["ن", "ب", "ت", "ل"],
      },
      {
        visualCue: "حـ_يقة",
        targetToken: "د",
        distractorTokens: ["ذ", "ز", "ر", "ب"],
      },
      {
        visualCue: "سـ_ارة",
        targetToken: "ي",
        distractorTokens: ["ا", "و", "ن", "ب"],
      },
      {
        visualCue: "مـ_تبة",
        targetToken: "ك",
        distractorTokens: ["ق", "خ", "ف", "ج"],
      },
      {
        visualCue: "تـ_اج",
        targetToken: "ف",
        distractorTokens: ["ق", "ك", "ب", "ن"],
      },
      {
        visualCue: "نـ_م",
        targetToken: "ج",
        distractorTokens: ["ح", "خ", "ع", "غ"],
      },
      {
        visualCue: "رـ_حة",
        targetToken: "ا",
        distractorTokens: ["و", "ي", "ن", "م"],
      },
    ],
  },
  {
    id: "q23",
    title: "السؤال 23",
    prompt: "اضغط على الحرف الخاطئ داخل الكلمة",
    instruction: "اقرأ الكلمة وحدد الحرف الذي لا ينتمي إليها",
    audioText: "اضغط على الحرف الخاطئ",
    interactionType: "wordLetters",
    visualCue: "بيتز",
    gridSize: 3,
    targetToken: "ز",
    distractorTokens: ["ب", "ي", "ت"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "قلام",
        targetToken: "ا",
        distractorTokens: ["ق", "ل", "م"],
      },
      {
        visualCue: "مدرصة",
        targetToken: "ص",
        distractorTokens: ["م", "د", "ر", "ة"],
      },
      {
        visualCue: "شجزة",
        targetToken: "ز",
        distractorTokens: ["ش", "ج", "ة"],
      },
      {
        visualCue: "نافذةن",
        targetToken: "ن",
        distractorTokens: ["ا", "ف", "ذ", "ة"],
      },
      {
        visualCue: "كتاثب",
        targetToken: "ث",
        distractorTokens: ["ك", "ت", "ا", "ب"],
      },
      {
        visualCue: "مكتضة",
        targetToken: "ض",
        distractorTokens: ["م", "ك", "ت", "ب", "ة"],
      },
      {
        visualCue: "سياذة",
        targetToken: "ذ",
        distractorTokens: ["س", "ي", "ا", "ة"],
      },
      {
        visualCue: "حديفقة",
        targetToken: "ف",
        distractorTokens: ["ح", "د", "ي", "ق", "ة"],
      },
      {
        visualCue: "وردغة",
        targetToken: "غ",
        distractorTokens: ["و", "ر", "د", "ة"],
      },
      {
        visualCue: "مصتاح",
        targetToken: "ص",
        distractorTokens: ["م", "ت", "ا", "ح"],
      },
      {
        visualCue: "قهلم",
        targetToken: "ه",
        distractorTokens: ["ق", "ل", "م"],
      },
    ],
  },
  {
    id: "q24",
    title: "السؤال 24",
    prompt: "اضغط على الكلمة التي لا تناسب معنى الجملة",
    instruction: "اقرأ الجملة وحدد الكلمة التي لا تنتمي إليها",
    audioText: "اضغط على الكلمة غير المناسبة",
    interactionType: "sentenceWords",
    visualCue: "ذهب سامي إلى المخبز ليشتري قلم",
    gridSize: 3,
    targetToken: "قلم",
    distractorTokens: ["ذهب", "سامي", "إلى", "المخبز", "ليشتري"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "فتحت مريم المظلة لأن الجو مشمس",
        targetToken: "المظلة",
        distractorTokens: ["فتحت", "مريم", "لأن", "الجو", "مشمس"],
      },
      {
        visualCue: "وضع الطفل الحساء في الثلاجة ليصبح ساخناً",
        targetToken: "ساخناً",
        distractorTokens: ["وضع", "الطفل", "الحساء", "في", "الثلاجة", "ليصبح"],
      },
      {
        visualCue: "كتب المعلم الدرس على كوب كبير",
        targetToken: "كوب",
        distractorTokens: ["كتب", "المعلم", "الدرس", "على", "كبير"],
      },
    ],
  },
  {
    id: "q25",
    title: "السؤال 25",
    prompt: "اضغط على الكلمة النحوية الخاطئة في الجملة",
    instruction: "اقرأ الجملة وحدد الخطأ النحوي",
    audioText: "اضغط على الكلمة الخاطئة نحوياً",
    interactionType: "sentenceWords",
    visualCue: "هو مهتم على الموسيقى",
    gridSize: 3,
    targetToken: "على",
    distractorTokens: ["هو", "مهتم", "الموسيقى"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "اعطيت الكتاب على صديقي",
        targetToken: "على",
        distractorTokens: ["اعطيت", "الكتاب", "صديقي"],
      },
      {
        visualCue: "نحن ننتظر من الحافلة كل صباح",
        targetToken: "من",
        distractorTokens: ["نحن", "ننتظر", "الحافلة", "كل", "صباح"],
      },
      {
        visualCue: "استمعت على القصة قبل النوم",
        targetToken: "على",
        distractorTokens: ["استمعت", "القصة", "قبل", "النوم"],
      },
    ],
  },
  {
    id: "q26",
    title: "السؤال 26",
    prompt: "حدد الحرف الخاطئ في الكلمة ثم اختر الحرف الصحيح",
    instruction: "اضغط على الحرف الخاطئ أولاً ثم اختر بديله الصحيح",
    audioText: "صحح الحرف الخاطئ في الكلمة",
    interactionType: "letterReplacement",
    visualCue: "بيث",
    gridSize: 3,
    targetToken: "بيت",
    distractorTokens: ["بيث"],
    correctionTargetToken: "ت",
    correctionDistractorTokens: ["ب", "ن", "ذ", "ز"],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "كتاث",
        targetToken: "كتاب",
        distractorTokens: ["كتاث"],
        correctionTargetToken: "ب",
        correctionDistractorTokens: ["ن", "ت", "ي", "و"],
      },
      {
        visualCue: "شجزة",
        targetToken: "شجرة",
        distractorTokens: ["شجزة"],
        correctionTargetToken: "ر",
        correctionDistractorTokens: ["د", "ذ", "ن", "و"],
      },
      {
        visualCue: "قنم",
        targetToken: "قلم",
        distractorTokens: ["قنم"],
        correctionTargetToken: "ل",
        correctionDistractorTokens: ["ر", "ب", "م", "ت"],
      },
      {
        visualCue: "مذرسة",
        targetToken: "مدرسة",
        distractorTokens: ["مذرسة"],
        correctionTargetToken: "د",
        correctionDistractorTokens: ["ر", "ز", "ب", "ت"],
      },
      {
        visualCue: "وزدة",
        targetToken: "وردة",
        distractorTokens: ["وزدة"],
        correctionTargetToken: "ر",
        correctionDistractorTokens: ["د", "ذ", "ب", "ن"],
      },
      {
        visualCue: "مكتضة",
        targetToken: "مكتبة",
        distractorTokens: ["مكتضة"],
        correctionTargetToken: "ب",
        correctionDistractorTokens: ["ت", "ن", "ث", "ي"],
      },
      {
        visualCue: "سيازة",
        targetToken: "سيارة",
        distractorTokens: ["سيازة"],
        correctionTargetToken: "ر",
        correctionDistractorTokens: ["د", "ذ", "و", "ن"],
      },
      {
        visualCue: "مصتاح",
        targetToken: "مفتاح",
        distractorTokens: ["مصتاح"],
        correctionTargetToken: "ف",
        correctionDistractorTokens: ["ق", "ك", "ب", "ت"],
      },
    ],
  },
  {
    id: "q27",
    title: "السؤال 27",
    prompt: "رتب الحروف لتكوين الكلمة الصحيحة",
    instruction: "اضغط على الحروف بالترتيب الصحيح لتكوين الكلمة",
    audioText: "رتب الحروف لتكوين الكلمة",
    interactionType: "letterArrangement",
    visualCue: "م,د,ر,س,ة",
    gridSize: 3,
    targetToken: "مدرسة",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "ك,ت,ا,ب",
        targetToken: "كتاب",
        distractorTokens: [],
      },
      {
        visualCue: "ق,ل,م",
        targetToken: "قلم",
        distractorTokens: [],
      },
      {
        visualCue: "ن,ا,ف,ذ,ة",
        targetToken: "نافذة",
        distractorTokens: [],
      },
      {
        visualCue: "ح,د,ي,ق,ة",
        targetToken: "حديقة",
        distractorTokens: [],
      },
    ],
  },
  {
    id: "q28",
    title: "السؤال 28",
    prompt: "رتب المقاطع لتكوين الكلمة الصحيحة",
    instruction: "اضغط على المقاطع بالترتيب الصحيح",
    audioText: "رتب المقاطع لتكوين الكلمة",
    interactionType: "syllableArrangement",
    visualCue: "مدر,سة",
    gridSize: 3,
    targetToken: "مدرسة",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "مك,تبة",
        targetToken: "مكتبة",
        distractorTokens: [],
      },
      {
        visualCue: "سي,ارة",
        targetToken: "سيارة",
        distractorTokens: [],
      },
      {
        visualCue: "فا,كهة",
        targetToken: "فاكهة",
        distractorTokens: [],
      },
      {
        visualCue: "مص,باح",
        targetToken: "مصباح",
        distractorTokens: [],
      },
    ],
  },
  {
    id: "q29",
    title: "السؤال 29",
    prompt: "اختر الجملة المكتوبة بشكل صحيح مع المسافات",
    instruction:
      "النص بدون مسافات — اختر النسخة الصحيحة التي تضع المسافات في مكانها الصحيح",
    audioText: "اختر الجملة المفصولة بشكل صحيح",
    interactionType: "sentenceSegmentationChoices",
    choiceCount: 4,
    visualCue: "ذهبتالىالمدرسةاليوم",
    gridSize: 2,
    targetToken: "ذهبت الى المدرسة اليوم",
    distractorTokens: [
      "ذهبتالى المدرسة اليوم",
      "ذهبت الىالمدرسة اليوم",
      "ذهبت الى المدرسةاليوم",
    ],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "يقرأاخيالكتابكلليلة",
        targetToken: "يقرأ اخي الكتاب كل ليلة",
        distractorTokens: [
          "يقرأاخي الكتاب كل ليلة",
          "يقرأ اخيالكتاب كل ليلة",
          "يقرأ اخي الكتابكل ليلة",
        ],
      },
      {
        visualCue: "يلعبالاطفالفيساحةالبيت",
        targetToken: "يلعب الاطفال في ساحة البيت",
        distractorTokens: [
          "يلعبالاطفال في ساحة البيت",
          "يلعب الاطفالفي ساحة البيت",
          "يلعب الاطفال فيساحة البيت",
        ],
      },
      {
        visualCue: "كتبتالمعلمةالواجبعلىالسبورة",
        targetToken: "كتبت المعلمة الواجب على السبورة",
        distractorTokens: [
          "كتبتالمعلمة الواجب على السبورة",
          "كتبت المعلمةالواجب على السبورة",
          "كتبت المعلمة الواجبعلى السبورة",
        ],
      },
      {
        visualCue: "يغسلالطفليديهقبلالطعام",
        targetToken: "يغسل الطفل يديه قبل الطعام",
        distractorTokens: [
          "يغسلالطفل يديه قبل الطعام",
          "يغسل الطفليديه قبل الطعام",
          "يغسل الطفل يديهقبل الطعام",
        ],
      },
      {
        visualCue: "شاهدنافلماجميلابعدالعشاء",
        targetToken: "شاهدنا فلما جميلا بعد العشاء",
        distractorTokens: [
          "شاهدنافلما جميلا بعد العشاء",
          "شاهدنا فلماجميلا بعد العشاء",
          "شاهدنا فلما جميلابعد العشاء",
        ],
      },
      {
        visualCue: "يحملساميحقيبةزرقاء",
        targetToken: "يحمل سامي حقيبة زرقاء",
        distractorTokens: [
          "يحملسامي حقيبة زرقاء",
          "يحمل ساميحقيبة زرقاء",
          "يحمل سامي حقيبةزرقاء",
        ],
      },
      {
        visualCue: "نرتبالكتببعدالدراسة",
        targetToken: "نرتب الكتب بعد الدراسة",
        distractorTokens: [
          "نرتبالكتب بعد الدراسة",
          "نرتب الكتببعد الدراسة",
          "نرتب الكتب بعدالدراسة",
        ],
      },
      {
        visualCue: "يرسمراميشجرةفيالحديقة",
        targetToken: "يرسم رامي شجرة في الحديقة",
        distractorTokens: [
          "يرسمرامي شجرة في الحديقة",
          "يرسم راميشجرة في الحديقة",
          "يرسم رامي شجرةفي الحديقة",
        ],
      },
      {
        visualCue: "يسقيابيالزهوركلصباح",
        targetToken: "يسقي ابي الزهور كل صباح",
        distractorTokens: [
          "يسقيابي الزهور كل صباح",
          "يسقي ابيالزهور كل صباح",
          "يسقي ابي الزهوركل صباح",
        ],
      },
    ],
  },
  {
    id: "q30",
    title: "السؤال 30",
    prompt: "احفظ تسلسل الحروف ثم اكتبه من الذاكرة",
    instruction: "ستظهر الحروف لمدة 3 ثوان فقط، ثم اكتبها",
    audioText: "احفظ ثم اكتب",
    interactionType: "typedSequenceRecall",
    visualCue: "ن ب ر",
    gridSize: 3,
    targetToken: "نبر",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "د ا ف و",
        targetToken: "دافو",
        distractorTokens: [],
      },
      {
        visualCue: "س ق ي ر",
        targetToken: "سقير",
        distractorTokens: [],
      },
      {
        visualCue: "م ت ر ن",
        targetToken: "مترن",
        distractorTokens: [],
      },
    ],
  },
  {
    id: "q31",
    title: "السؤال 31",
    prompt: "استمع إلى الكلمة واكتبها كما سمعتها",
    instruction: "ستسمع كلمة حقيقية، اكتبها بشكل صحيح",
    audioText: "استمع واكتب الكلمات",
    interactionType: "typedSequenceRecall",
    visualCue: "",
    gridSize: 3,
    targetToken: "شمس",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "",
        targetToken: "وردة",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "نافذة",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "مكتبة",
        distractorTokens: [],
      },
    ],
  },
  {
    id: "q32",
    title: "السؤال 32",
    prompt: "استمع إلى الكلمة غير الحقيقية واكتبها كما سمعتها",
    instruction: "ستسمع كلمة غير حقيقية، اكتبها بشكل صحيح كما سمعتها بالضبط",
    audioText: "استمع واكتب الكلمات غير الحقيقية",
    interactionType: "typedSequenceRecall",
    visualCue: "",
    gridSize: 3,
    targetToken: "سارن",
    distractorTokens: [],
    targetRepeatCount: 1,
    variants: [
      {
        visualCue: "",
        targetToken: "كلفد",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "منبور",
        distractorTokens: [],
      },
      {
        visualCue: "",
        targetToken: "راثب",
        distractorTokens: [],
      },
    ],
  },
];
